'use client';

import React, { useState } from 'react';
import Sidebar from '@/components/Sidebar';
import { useRouter } from 'next/navigation';

export default function ApiDocsPage() {
  const router = useRouter();
  const [apiKey, setApiKey] = useState('al_live_58c2d9a6f1e8a49c2b0c3d9e');
  const [isCopied, setIsCopied] = useState(false);

  const handleCopyKey = () => {
    navigator.clipboard.writeText(apiKey);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleNavClick = (tabName: string) => {
    if (tabName === 'Dashboard') {
      router.push('/dashboard');
    } else if (tabName === 'Watchlist') {
      router.push('/dashboard?tab=Watchlist');
    } else if (tabName === 'Backtest') {
      router.push('/backtest');
    } else if (tabName === 'Risk') {
      router.push('/risk');
    } else if (tabName === 'API') {
      router.push('/api-docs');
    }
  };

  // Endpoint Details
  const endpoints = [
    {
      method: 'GET',
      path: '/api/v1/signals',
      desc: 'Retrieve all live and historical confluence signals generated by the machine learning engine, sorted by confidence score.',
      response: `{
  "success": true,
  "signals": [
    {
      "id": "TICKER#AAPL_SIGNAL#2026-06-26T12:00:00Z",
      "ticker": "AAPL",
      "market": "US",
      "signalType": "BUY",
      "confidence": 85,
      "entry": 189.20,
      "stopLoss": 185.00,
      "target": 198.00,
      "timestamp": "2 min ago"
    },
    {
      "id": "TICKER#RELIANCE.NS_SIGNAL#2026-06-26T11:45:00Z",
      "ticker": "RELIANCE.NS",
      "market": "NSE",
      "signalType": "BUY",
      "confidence": 81,
      "entry": 2847.50,
      "stopLoss": 2790.00,
      "target": 2960.00,
      "timestamp": "17 min ago"
    }
  ]
}`
    },
    {
      method: 'GET',
      path: '/api/v1/signals/{ticker}',
      desc: 'Fetch the latest active trade signal details, levels, and confidence rating for a specific equity ticker.',
      response: `{
  "success": true,
  "signal": {
    "ticker": "RELIANCE.NS",
    "market": "NSE",
    "signalType": "BUY",
    "confidence": 81,
    "entry": 2847.50,
    "stopLoss": 2790.00,
    "target": 2960.00,
    "timestamp": "5 min ago"
  }
}`
    },
    {
      method: 'GET',
      path: '/api/v1/backtest/{ticker}',
      desc: 'Retrieve strategy validation backtest logs and key performance indicators (Accuracy, Win Rate, and Avg R:R) for a ticker.',
      response: `{
  "success": true,
  "accuracy": 73,
  "winRate": 68,
  "avgRR": 2.1,
  "signals": [
    {
      "id": "mock_0",
      "date": "Jun 24, 2026",
      "signal": "BUY",
      "entry": 2847.50,
      "exit": 2961.40,
      "result": "WIN",
      "pnl": 4.00
    },
    {
      "id": "mock_1",
      "date": "Jun 20, 2026",
      "signal": "SELL",
      "entry": 2810.00,
      "exit": 2866.20,
      "result": "LOSS",
      "pnl": -2.00
    }
  ]
}`
    }
  ];

  // Mobile Bottom Nav items list
  const navItems = [
    { name: 'Dashboard', icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v4a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v4a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v4a2 2 0 01-2 2H6a2 2 0 01-2-2v-4zM14 16a2 2 0 012-2h2a2 2 0 012 2v4a2 2 0 01-2 2h-2a2 2 0 01-2-2v-4z" />
      </svg>
    )},
    { name: 'Watchlist', icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.907c.961 0 1.36 1.237.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
      </svg>
    )},
    { name: 'Backtest', icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
      </svg>
    )},
    { name: 'Risk', icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
      </svg>
    )},
    { name: 'API', icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
      </svg>
    )},
  ];

  return (
    <div className="min-h-screen bg-void text-frost flex flex-col font-sans">
      {/* Desktop Sidebar */}
      <Sidebar activeTab="API" />

      {/* Main Content Area */}
      <main className="flex-1 md:pl-[220px] p-6 pb-28 md:pb-6 max-w-5xl w-full mx-auto">
        
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-[20px] font-medium text-frost mb-1.5 font-brand leading-none">
            Alphaline API
          </h1>
          <p className="text-[13px] text-muted font-sans font-normal leading-normal">
            Trading signals for your product. Integrate machine learning confluences directly.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
          
          {/* Left Panel: Auth Credentials & Rate Limits */}
          <div className="lg:col-span-1 space-y-6">
            
            {/* API Key Panel */}
            <div className="bg-surface border border-border-dark p-5 rounded-[6px] space-y-4">
              <h3 className="text-[14px] font-medium text-frost leading-none">
                Your API Credentials
              </h3>
              
              <div className="space-y-2">
                <label className="block text-[11px] text-dim font-sans uppercase tracking-wider font-semibold">
                  API Key
                </label>
                
                <div className="flex gap-2">
                  <input
                    type="text"
                    readOnly
                    value="al_live_••••••••••••••••"
                    className="w-full bg-raised border border-border-dark text-[12px] text-muted p-2 rounded-[6px] font-mono focus:outline-none"
                  />
                  <button
                    onClick={handleCopyKey}
                    className="bg-indigo text-white text-[12px] font-medium px-4 rounded-[6px] hover:bg-[#5254DE] transition-colors duration-150 font-sans"
                  >
                    {isCopied ? 'Copied' : 'Copy'}
                  </button>
                </div>
              </div>
            </div>

            {/* Rate Limits Table */}
            <div className="bg-surface border border-border-dark rounded-[6px] overflow-hidden">
              <div className="border-b border-border-dark p-3.5 bg-[#131720]">
                <h3 className="text-[12px] font-semibold text-frost font-sans uppercase tracking-wider">
                  API Rate Limits
                </h3>
              </div>
              
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-void border-b border-border-dark">
                      <th className="p-3 text-[10px] font-normal text-dim uppercase tracking-wider font-sans">Tier</th>
                      <th className="p-3 text-[10px] font-normal text-dim uppercase tracking-wider font-sans text-right">Quota / Mo</th>
                      <th className="p-3 text-[10px] font-normal text-dim uppercase tracking-wider font-sans text-right">Rate</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#1E2230]/50 font-sans text-[12px] text-frost">
                    {[
                      { tier: 'FREE', quota: '1,000', rate: '1/sec' },
                      { tier: 'PRO', quota: '100,000', rate: '10/sec' },
                      { tier: 'PARTNER', quota: 'UNLIMITED', rate: 'CUSTOM' }
                    ].map((row, idx) => (
                      <tr 
                        key={idx}
                        className={`transition-colors duration-150 hover:bg-raised ${
                          idx % 2 === 0 ? 'bg-transparent' : 'bg-void/40'
                        }`}
                      >
                        <td className="p-3 font-semibold text-frost">{row.tier}</td>
                        <td className="p-3 font-mono text-right text-muted">{row.quota}</td>
                        <td className="p-3 font-mono text-right text-indigo">{row.rate}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

          </div>

          {/* Right Panel: Endpoint Documentation Cards */}
          <div className="lg:col-span-2 space-y-6">
            
            {endpoints.map((ep, idx) => (
              <div 
                key={idx}
                className="bg-surface border border-border-dark rounded-[6px] overflow-hidden"
              >
                {/* Endpoint Header */}
                <div className="border-b border-border-dark p-4 bg-[#131720] flex flex-wrap items-center justify-between gap-3">
                  <div className="flex items-center gap-2.5">
                    <span className="text-[10px] px-2 py-0.5 bg-indigo/10 border border-indigo/20 text-indigo font-bold rounded-[4px] font-sans">
                      {ep.method}
                    </span>
                    <span className="font-mono text-[13px] font-medium text-indigo">
                      {ep.path}
                    </span>
                  </div>
                </div>

                {/* Description */}
                <div className="p-4 border-b border-border-dark/40 bg-void/10">
                  <p className="text-[12.5px] text-muted leading-relaxed font-sans">
                    {ep.desc}
                  </p>
                </div>

                {/* Code Block Response */}
                <div className="p-4 bg-void">
                  <div className="flex justify-between items-center text-[10px] text-dim uppercase tracking-wider mb-2 font-semibold">
                    <span>Response Payload (JSON)</span>
                  </div>
                  
                  <pre className="bg-void border border-[#1E2230] rounded-[6px] p-4 overflow-x-auto text-[12px] text-[#E2E8F0] font-mono leading-relaxed max-h-[220px]">
                    <code>{ep.response}</code>
                  </pre>
                </div>
              </div>
            ))}

          </div>

        </div>
      </main>

      {/* Mobile Bottom Nav */}
      <nav className="fixed bottom-0 left-0 right-0 h-16 border-t border-border-dark bg-surface flex justify-around items-center md:hidden z-20">
        {navItems.map((item) => {
          const isActive = item.name === 'API';
          return (
            <button
              key={item.name}
              onClick={() => handleNavClick(item.name)}
              className={`flex flex-col items-center justify-center w-12 h-full transition-colors duration-150 ${
                isActive ? 'text-indigo' : 'text-muted hover:text-frost'
              }`}
            >
              {item.icon}
              <span className="text-[10px] font-sans mt-0.5 font-medium">{item.name}</span>
            </button>
          );
        })}
      </nav>
    </div>
  );
}
