'use client';

import React, { useState, useEffect } from 'react';
import Sidebar from '@/components/Sidebar';
import { useRouter } from 'next/navigation';
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { toast } from 'sonner';
import { Star, ShieldAlert, Key, Clipboard, Trash2, ArrowUpRight, Plus, Terminal, LayoutDashboard, Activity } from 'lucide-react';

interface ApiKey {
  id: string;
  name: string;
  key: string;
  created: string;
  status: 'ACTIVE' | 'REVOKED';
}

export default function ApiDocsPage() {
  const router = useRouter();
  const [mounted, setMounted] = useState(false);
  const [apiKeys, setApiKeys] = useState<ApiKey[]>([]);
  const [newKeyName, setNewKeyName] = useState("");
  const [isCopiedId, setIsCopiedId] = useState<string | null>(null);

  // Default Stats Mock
  const requestStats = [
    { day: "Mon", requests: 120 },
    { day: "Tue", requests: 340 },
    { day: "Wed", requests: 480 },
    { day: "Thu", requests: 620 },
    { day: "Fri", requests: 880 },
    { day: "Sat", requests: 510 },
    { day: "Sun", requests: 478 },
  ];

  useEffect(() => {
    setMounted(true);
    document.title = "Alphaline — API Documentation";

    // Load keys from LocalStorage
    if (typeof window !== 'undefined') {
      const storedKeys = localStorage.getItem('alphaline_api_keys');
      if (storedKeys) {
        setApiKeys(JSON.parse(storedKeys));
      } else {
        const defaultKeys: ApiKey[] = [
          {
            id: "key_1",
            name: "Default Live Key",
            key: "al_live_58c2d9a6f1e8a49c2b0c3d9e",
            created: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }),
            status: "ACTIVE",
          }
        ];
        setApiKeys(defaultKeys);
        localStorage.setItem('alphaline_api_keys', JSON.stringify(defaultKeys));
      }
    }
  }, []);

  const saveKeys = (newKeys: ApiKey[]) => {
    setApiKeys(newKeys);
    localStorage.setItem('alphaline_api_keys', JSON.stringify(newKeys));
  };

  const handleGenerateKey = () => {
    if (!newKeyName.trim()) {
      toast.error("Enter a name for the API key.");
      return;
    }

    const randomHex = Array.from({ length: 24 }, () => 
      Math.floor(Math.random() * 16).toString(16)
    ).join('');
    
    const newKey: ApiKey = {
      id: `key_${Date.now()}`,
      name: newKeyName,
      key: `al_live_${randomHex}`,
      created: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }),
      status: "ACTIVE",
    };

    const nextKeys = [...apiKeys, newKey];
    saveKeys(nextKeys);
    setNewKeyName("");
    toast.success(`Generated API key "${newKey.name}"`);
  };

  const handleRevokeKey = (id: string) => {
    const updated = apiKeys.map(k => {
      if (k.id === id) {
        return { ...k, status: 'REVOKED' as const };
      }
      return k;
    });
    saveKeys(updated);
    toast.success("API key revoked.");
  };

  const handleCopyKey = (key: string, id: string) => {
    navigator.clipboard.writeText(key);
    setIsCopiedId(id);
    toast.success("Key copied to clipboard.");
    setTimeout(() => setIsCopiedId(null), 2000);
  };

  const handleNavClick = (tabName: string) => {
    if (tabName === 'Dashboard') {
      router.push('/dashboard');
    } else if (tabName === 'Watchlist') {
      router.push('/dashboard?tab=Watchlist');
    } else if (tabName === 'Backtest') {
      router.push('/backtest');
    } else if (tabName === 'Risk') {
      router.push('/risk');
    } else if (tabName === 'API') {
      router.push('/api-docs');
    }
  };

  // Endpoint Details
  const endpoints = [
    {
      method: 'GET',
      path: '/api/v1/signals',
      desc: 'Retrieve all live and historical confluence signals generated by the machine learning engine, sorted by confidence score.',
      response: `{
  "success": true,
  "signals": [
    {
      "id": "TICKER#AAPL_SIGNAL#2026-06-26T12:00:00Z",
      "ticker": "AAPL",
      "market": "US",
      "signalType": "BUY",
      "confidence": 85,
      "entry": 189.20,
      "stopLoss": 185.00,
      "target": 198.00,
      "timestamp": "2 min ago"
    },
    {
      "id": "TICKER#RELIANCE.NS_SIGNAL#2026-06-26T11:45:00Z",
      "ticker": "RELIANCE.NS",
      "market": "NSE",
      "signalType": "BUY",
      "confidence": 81,
      "entry": 2847.50,
      "stopLoss": 2790.00,
      "target": 2960.00,
      "timestamp": "17 min ago"
    }
  ]
}`
    },
    {
      method: 'GET',
      path: '/api/v1/signals/{ticker}',
      desc: 'Fetch the latest active trade signal details, levels, and confidence rating for a specific equity ticker.',
      response: `{
  "success": true,
  "signal": {
    "ticker": "RELIANCE.NS",
    "market": "NSE",
    "signalType": "BUY",
    "confidence": 81,
    "entry": 2847.50,
    "stopLoss": 2790.00,
    "target": 2960.00,
    "timestamp": "5 min ago"
  }
}`
    },
    {
      method: 'GET',
      path: '/api/v1/backtest/{ticker}',
      desc: 'Retrieve strategy validation backtest logs and key performance indicators (Accuracy, Win Rate, and Avg R:R) for a ticker.',
      response: `{
  "success": true,
  "accuracy": 73,
  "winRate": 68,
  "avgRR": 2.1,
  "signals": [
    {
      "id": "mock_0",
      "date": "Jun 24, 2026",
      "signal": "BUY",
      "entry": 2847.50,
      "exit": 2961.40,
      "result": "WIN",
      "pnl": 4.00
    },
    {
      "id": "mock_1",
      "date": "Jun 20, 2026",
      "signal": "SELL",
      "entry": 2810.00,
      "exit": 2866.20,
      "result": "LOSS",
      "pnl": -2.00
    }
  ]
}`
    }
  ];

  // Mobile Bottom Nav items list
  const navItems = [
    { name: 'Dashboard', icon: <LayoutDashboard className="w-5 h-5" /> },
    { name: 'Watchlist', icon: <Star className="w-5 h-5" /> },
    { name: 'Backtest', icon: <Activity className="w-5 h-5" /> },
    { name: 'Risk', icon: <ShieldAlert className="w-5 h-5" /> },
    { name: 'API', icon: <Terminal className="w-5 h-5" /> },
  ];

  return (
    <div className="min-h-screen bg-void text-frost flex flex-col font-sans">
      <Sidebar activeTab="API" />

      <main className="flex-1 md:pl-[220px] p-6 pb-28 md:pb-6 max-w-5xl w-full mx-auto">
        
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-[20px] font-medium text-frost mb-1.5 font-brand leading-none">
            Developer API Hub
          </h1>
          <p className="text-[13px] text-muted font-sans font-normal leading-normal">
            Manage your credentials, monitor request rates, and integrate signals into your systems.
          </p>
        </div>

        {/* Top Usage Statistics Row */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6 items-start">
          
          {/* Key Manager Box */}
          <div className="lg:col-span-2 space-y-4">
            <div className="bg-[#111318]/50 backdrop-blur-md border border-border-dark p-5 rounded-[6px] space-y-4">
              <div className="flex justify-between items-center border-b border-[#1E2230]/40 pb-2">
                <h3 className="text-[13px] font-bold text-muted uppercase tracking-wider leading-none">
                  API Key Management
                </h3>
                <div className="flex gap-2">
                  <input
                    type="text"
                    placeholder="Key Label (e.g. Production)"
                    value={newKeyName}
                    onChange={e => setNewKeyName(e.target.value)}
                    className="bg-void border border-border-dark text-[11px] text-frost px-2.5 py-1 rounded focus:outline-none focus:border-indigo"
                  />
                  <button
                    onClick={handleGenerateKey}
                    className="bg-indigo hover:bg-[#5254DE] text-white px-2.5 py-1 text-[11px] font-medium rounded flex items-center gap-1 transition-colors leading-none"
                  >
                    <Plus size={12} /> Generate Key
                  </button>
                </div>
              </div>

              {/* Active Keys Table */}
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="border-b border-[#1E2230]/40 select-none">
                      <th className="pb-2 text-[10px] text-dim uppercase tracking-wider font-sans">Name</th>
                      <th className="pb-2 text-[10px] text-dim uppercase tracking-wider font-sans font-mono">Key Secret</th>
                      <th className="pb-2 text-[10px] text-dim uppercase tracking-wider font-sans text-center">Status</th>
                      <th className="pb-2 text-[10px] text-dim uppercase tracking-wider font-sans text-right">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#1E2230]/20 font-sans text-[12.5px] text-[#E2E8F0]">
                    {apiKeys.map((k) => (
                      <tr key={k.id} className="hover:bg-[#1C1F28]/30 transition-colors">
                        <td className="py-2.5 pr-2 font-medium">{k.name}</td>
                        <td className="py-2.5 pr-2 font-mono text-muted text-[11.5px] select-all">
                          {k.status === 'ACTIVE' ? k.key : '••••••••••••••••••••••••'}
                        </td>
                        <td className="py-2.5 text-center">
                          <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded ${
                            k.status === 'ACTIVE' 
                              ? 'text-sig-green bg-sig-green/5 border border-sig-green/10'
                              : 'text-dim bg-raised/20 border border-border-dark'
                          }`}>
                            {k.status}
                          </span>
                        </td>
                        <td className="py-2.5 text-right space-x-1">
                          {k.status === 'ACTIVE' && (
                            <>
                              <button
                                onClick={() => handleCopyKey(k.key, k.id)}
                                className="text-muted hover:text-indigo p-1 rounded transition-colors inline-flex items-center justify-center"
                                title="Copy Key"
                              >
                                <Clipboard size={12} />
                              </button>
                              <button
                                onClick={() => handleRevokeKey(k.id)}
                                className="text-muted hover:text-sig-red p-1 rounded transition-colors inline-flex items-center justify-center"
                                title="Revoke Key"
                              >
                                <Trash2 size={12} />
                              </button>
                            </>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* Usage Chart Panel */}
          <div className="lg:col-span-1 space-y-4 bg-[#111318]/40 border border-border-dark p-4 rounded-[6px]">
            <span className="text-[11px] font-bold text-muted uppercase tracking-wider block">
              API Requests (Last 7 Days)
            </span>
            
            <div className="w-full h-[120px]">
              {mounted && (
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={requestStats} margin={{ top: 5, right: 5, left: 5, bottom: 5 }}>
                    <defs>
                      <linearGradient id="apiChartGradient" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="#6366F1" stopOpacity="0.2"/>
                        <stop offset="100%" stopColor="#6366F1" stopOpacity="0.0"/>
                      </linearGradient>
                    </defs>
                    <XAxis 
                      dataKey="day" 
                      axisLine={false} 
                      tickLine={false} 
                      tick={{ fill: '#374151', fontSize: 10, fontFamily: 'var(--font-jetbrains-mono)' }} 
                    />
                    <YAxis hide={true} />
                    <Tooltip 
                      contentStyle={{ backgroundColor: '#111318', borderColor: '#1E2230', borderRadius: '6px', color: '#E2E8F0', fontSize: '10px' }}
                    />
                    <Area 
                      type="monotone" 
                      dataKey="requests" 
                      stroke="#6366F1" 
                      strokeWidth={1.5} 
                      fill="url(#apiChartGradient)" 
                    />
                  </AreaChart>
                </ResponsiveContainer>
              )}
            </div>
            
            <div className="grid grid-cols-2 gap-4 border-t border-[#1E2230] pt-3 text-left">
              <div>
                <span className="block text-[9px] text-dim uppercase tracking-wide">Usage Limit</span>
                <span className="font-mono text-frost font-medium text-[13px]">3,428 / 10,000 reqs</span>
              </div>
              <div>
                <span className="block text-[9px] text-dim uppercase tracking-wide">Avg Latency</span>
                <span className="font-mono text-indigo font-medium text-[13px]">42 ms</span>
              </div>
            </div>
          </div>

        </div>

        {/* Bottom Documentation Section */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
          
          {/* Rate Limits */}
          <div className="lg:col-span-1 bg-[#111318]/50 border border-border-dark rounded-[6px] overflow-hidden select-none">
            <div className="border-b border-border-dark p-3.5 bg-void">
              <h3 className="text-[11px] font-bold text-muted uppercase tracking-wider leading-none">
                Rate Quota Limits
              </h3>
            </div>
            
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-void/50 border-b border-border-dark">
                  <th className="p-3 text-[10px] font-normal text-dim uppercase tracking-wider font-sans">Tier</th>
                  <th className="p-3 text-[10px] font-normal text-dim uppercase tracking-wider font-sans text-right">Limit</th>
                  <th className="p-3 text-[10px] font-normal text-dim uppercase tracking-wider font-sans text-right">Burst Rate</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#1E2230]/50 font-sans text-[12px] text-frost">
                {[
                  { tier: 'FREE', quota: '1,000 / mo', rate: '1 req/s' },
                  { tier: 'PRO', quota: '100,000 / mo', rate: '10 req/s' },
                  { tier: 'PARTNER', quota: 'UNLIMITED', rate: 'CUSTOM' }
                ].map((row, idx) => (
                  <tr key={idx} className="hover:bg-[#1C1F28]/30 transition-colors">
                    <td className="p-3 font-semibold text-frost">{row.tier}</td>
                    <td className="p-3 font-mono text-right text-muted">{row.quota}</td>
                    <td className="p-3 font-mono text-right text-indigo">{row.rate}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Endpoint Documentation */}
          <div className="lg:col-span-2 space-y-6">
            {endpoints.map((ep, idx) => (
              <div 
                key={idx}
                className="bg-surface border border-border-dark rounded-[6px] overflow-hidden"
              >
                {/* Endpoint Header */}
                <div className="border-b border-border-dark p-4 bg-void flex flex-wrap items-center justify-between gap-3">
                  <div className="flex items-center gap-2.5">
                    <span className="text-[10px] px-2 py-0.5 bg-indigo/10 border border-indigo/20 text-indigo font-bold rounded-[4px] font-sans">
                      {ep.method}
                    </span>
                    <span className="font-mono text-[13px] font-medium text-indigo">
                      {ep.path}
                    </span>
                  </div>
                </div>

                {/* Description */}
                <div className="p-4 border-b border-[#1E2230]/40 bg-void/10">
                  <p className="text-[12.5px] text-muted leading-relaxed font-sans font-normal">
                    {ep.desc}
                  </p>
                </div>

                {/* Response Code Block */}
                <div className="p-4 bg-void">
                  <div className="flex justify-between items-center text-[10px] text-dim uppercase tracking-wider mb-2 font-semibold">
                    <span>Response Payload (JSON)</span>
                  </div>
                  
                  <pre className="bg-[#111318] border border-[#1E2230] rounded-[6px] p-4 overflow-x-auto text-[12px] text-[#E2E8F0] font-mono leading-relaxed max-h-[220px]">
                    <code>{ep.response}</code>
                  </pre>
                </div>
              </div>
            ))}
          </div>

        </div>
      </main>

      {/* Mobile Bottom Nav */}
      <nav className="fixed bottom-0 left-0 right-0 h-16 border-t border-border-dark bg-surface flex justify-around items-center md:hidden z-20">
        {navItems.map((item) => {
          const isActive = item.name === 'API';
          return (
            <button
              key={item.name}
              onClick={() => handleNavClick(item.name)}
              className={`flex flex-col items-center justify-center w-12 h-full transition-colors duration-150 ${
                isActive ? 'text-indigo' : 'text-muted hover:text-frost'
              }`}
            >
              {item.icon}
              <span className="text-[10px] font-sans mt-0.5 font-medium">{item.name}</span>
            </button>
          );
        })}
      </nav>
    </div>
  );
}
